---
- hosts:
    - mons
  gather_facts: True
  become: True
  tasks:
    - name: Create fiobench pool
      command: "ceph osd pool create fiobench {{ fiobench_pgnum | default(5) }} {{ fiobench_pgpnum | default(fiobench_pgnum | default(5)) }}"
      run_once: True
      when: fiobench_pool_name is not defined
    - name: Create benchmark ceph client
      command: "ceph auth get-or-create client.fiobench mon 'allow r' osd 'allow * pool={{ fiobench_pool_name | default('fiobench') }}'"
      when: inventory_hostname == groups['mons'][0]
      register: _ceph_benchmark_client
    - name: Set benchmark_client fact
      set_fact:
        ceph_benchmark_client: "{{ _ceph_benchmark_client }}"

- hosts: benchmark_hosts
  gather_facts: True
  become: True
  post_tasks:
    - name: Install benchmark package
      package:
        name: "{{ item }}"
        state: present
        use: "{{ ansible_pkg_mgr }}"
      with_items:
        - fio
        - rbd-nbd
        - xfsprogs
    - name: Write ceph benchmark client key to file
      copy:
        content: "{{ [hostvars[groups['mons'][0]]['ceph_benchmark_client']['stdout'], '\n'] | join('') }}"
        dest: "/etc/ceph/ceph.client.fiobench.keyring"
    - name: Create a ceph device for benchmarking
      command: "rbd create {{ fiobench_pool_name | default('fiobench') }}/{{ item }} -s {{ fiobench_size | default(2048) }} -n client.fiobench -k /etc/ceph/ceph.client.fiobench.keyring"
      with_items:
        - bench_direct
        - bench_file
    - name: Map nbd direct device
      command: "rbd-nbd map {{ fiobench_pool_name | default('fiobench') }}/bench_direct -k /etc/ceph/ceph.client.fiobench.keyring -n client.fiobench"
      register: _nbd_direct_device
    - name: Map nbd file device
      command: "rbd-nbd map {{ fiobench_pool_name | default('fiobench') }}/bench_file -k /etc/ceph/ceph.client.fiobench.keyring -n client.fiobench"
      register: _nbd_file_device
    - name: Set bench_device_name facts
      set_fact:
        bench_direct_device_name: "{{ _nbd_direct_device.stdout }}"
        bench_file_device_name: "{{ _nbd_file_device.stdout}}"
    - name: Create xfs file system on device
      filesystem:
        fstype: xfs
        device: "{{ item }}"
      with_items:
        - "{{ bench_direct_device_name }}"
        - "{{ bench_file_device_name }}"
    - name: Create benchmark directories
      file:
        state: directory
        path: "{{ item }}"
      with_items:
        - /opt/ceph_bench/logs
        - /mnt/fio_bench
    - name: Template out fio_bench files
      config_template:
        src: "templates/{{ item.name }}.j2"
        dest: "/opt/ceph_bench/{{ item.name }}"
        config_overrides: "{{ item.override }}"
        config_type: "ini"
      with_items:
        - name: "fio_direct_read_test.cfg"
          override: "{{ fio_direct_read_test_overrides | default({}) }}"
        - name: "fio_direct_write_test.cfg"
          override: "{{ fio_direct_write_test_overrides | default({}) }}"
        - name: "fio_rw_mix.cfg"
          override: "{{ fio_rw_mix_overrides | default({}) }}"
        - name: "fio_test_file_read.cfg"
          override: "{{ fio_test_file_read_overrides | default({}) }}"
        - name: "fio_test_file_write.cfg"
          override: "{{ fio_test_file_write_overrides | default({}) }}"
    # In py2 ConfigParser cant strip spaces around delimiters FIO needs that.
    - name: Manually strip spaces around delimiters
      shell: "sed -i 's/ = /=/g' /opt/ceph_bench/*.cfg"
    - name: Mount image
      mount:
        src: "{{ bench_file_device_name }}"
        fstype: "xfs"
        name: "/mnt/fio_bench"
        state: mounted
  roles:
    - ceph-defaults
    - ceph-common
    - ceph-config
    - ceph-client
