---
- hosts: benchmark_hosts
  become: True
  gather_facts: True
  tasks:
    - name: Run fio jobs and record version/config info
      shell: 'echo -e "FIO Version: `fio --version`\nFIO Config Used:\n`cat /opt/ceph_bench/{{ item.name }}.cfg `\n\nFIO Test Output:\n`fio /opt/ceph_bench/{{ item.name }}.cfg`" | tee /opt/ceph_bench/logs/{{ item.name }}.{{ ansible_date_time.iso8601_basic_short }}.log'
      register: fio_output
      with_items: "{{ fio_bench_list }}"
      when: item.run_bench
    - name: Debug fio outputs
      debug:
        var: item.stdout_lines
      with_items: "{{ fio_output.results }}"
