---
- name: Set CPU Governor
  import_playbook: tune-cpufreq.yml
  when: "{{ cpu_performance | default(true) }}"

- name: Deploy Ceph
  import_playbook: deploy-ceph.yml

# Remove after ceph-ansible > v3.1 is released
- name: Add modules to ceph-mgr
  import_playbook: add-mgr-modules.yml
  when: ceph_release_num[ceph_stable_release] >= ceph_release_num['luminous']

- name: Configure RGW HAProxy
  import_playbook: ceph-rgw-haproxy.yml
  when: "{{ rgw_haproxy | default(true) }}"

- name: Install ssacli
  import_playbook: ssacli-install.yml
  when: "{{ install_ssacli | default(false) }}"
