---
- hosts:
    - mons
    - osds
    - mgrs
    - rgws
    - mdss

  become: true

  roles:
    - name: prometheus_node_exporter

  post_tasks:
    - name: Write prometheus config
      template:
        src: node_targets.j2
        dest: /etc/prometheus/node_targets.yml
        owner: prometheus
        group: prometheus
      notify: restart prometheus
      delegate_to: "{{ item }}"
      with_items: "{{ groups.prometheus }}"

  handlers:
    - name: restart prometheus
      service:
        name: prometheus
        state: restarted
      delegate_to: "{{ item }}"
      with_items: "{{ groups.prometheus }}"
